### ISSUE TITLE
Update for Swift 3

### ISSUE THREAD

**Issue by SimplGy** [melke/SlimLogger#11]
Some differences with `@autoclosure`, the change from `NSCache` to `Cache<_,_>`, and other stuff I haven't checked out yet.

Have you started on this, or anybody else working on it?

**Comment by melke** [comment]
Hi @SimplGy 
No, I haven't started yet, and unfortunately I will have a hard time finding time to do it, so all pull requests are very welcome!

**Comment by jbarmanet** [comment]
@SimplGy I just pushed a swift 3 fork, feel free to grab it if you still need it...

**Comment by SimplGy** [comment]
Awesome, thanks man!

**Comment by melke** [comment]
Hi, the PR from  @jbarmanet is merged into master now. Thank you very much!
