### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by jyounus** [melke/SlimLogger#3]
Could you put this on CocoaPods please? Would be great if I could just add it to my pod file and use it. :)

Thanks

**Comment by jyounus** [comment]
Updating it to Swift 2 syntax would also be great and useful.

**Comment by melke** [comment]
Hi, and thanks for your feedback. Master is now updated to use Swift 2 syntax. Regarding CocoaPods, I feel that the project is so small, so adding a pod for it is a bit too early. It's basically just two files.  Maybe if the project grows.
